grafana:
  additionalDataSources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      isDefault: true
      jsonData:
        httpMethod: POST
        timeInterval: 30s
